sm8150-common: Add missing libfastrpc_utf_stub
error: vendor/lenovo/sm8150-common/Android.bp:1671:1: "libhbtpdsp" depends on undefined module "libfastrpc_utf_stub".
Change-Id: I62202a03ee7aab0c1555b8bfb93ce9e14c9ae66d