sm8150-common: Add missing TouchCompanion
error: vendor/lenovo/sm8150-common/Android.bp:1616:1: "libhbtpclient" depends on undefined module "vendor.qti.hardware.improvetouch.touchcompanion@1.0".
Change-Id: I2463836f7fe3def3949e3fea886d3bae8402b9a5